In [6]:
# (Матричное умножение) перемножьте матрицы A (2×3) и B (3×2) и выведите матрицу C и её форму.
# используйте матричное умножение A @ B (или np.dot(A, B)); проверьте C.shape.
import numpy as np
A = np.array(
    [[1,2,3],
    [4,5,6]
    ]
)
print(A)
B = np.array(
    [[10,20],
    [40,50],
    [70,80]]
)
print(B)
C = np.dot(A,B)
print(C)

[[1 2 3]
 [4 5 6]]
[[10 20]
 [40 50]
 [70 80]]
[[300 360]
 [660 810]]


In [ ]:
# транспонируйте матрицу M (2×3) и выведите T и T.shape.
# используйте свойство .T; у (m, n) транспонирование даёт (n, m).
M = np.array(
    [[1,2,3],
    [4,5,6]
    ])
T = M.T
print(T)

In [7]:
# выполните поэлементное умножение A и B одинаковой формы (2×3); выведите результат и форму.
# оператор * в NumPy выполняет поэлементное умножение (не матричное).
A = np.array(
    [[1,2,3],
    [4,5,6]
    ])
B = np.array(
    [[1,2,3],
    [4,5,6]
    ])
C = A*B
print(C)

[[ 1  4  9]
 [16 25 36]]


In [17]:
# из вектора x выберите только положительные элементы; выведите отобранный массив и его форму.
# постройте булеву маску (x > 0) и примените её как индекс: x[mask].
x = np.arange(-3,9)
print(x)
mask = x > 0
print(mask)
y = x[mask]
print(y)

[-3 -2 -1  0  1  2  3  4  5  6  7  8]
[False False False False  True  True  True  True  True  True  True  True]
[1 2 3 4 5 6 7 8]


In [19]:
# выберите из массива x только положительные чётные числа; выведите результат и его форму.
# комбинируйте условия скобками: (x > 0) & (x % 2 == 0).
x = np.arange(-3,9)
print(x)
mask = (x > 0) & (x % 2 == 0)
y = x[mask]
print(y)

[-3 -2 -1  0  1  2  3  4  5  6  7  8]
[2 4 6 8]


In [20]:
# в матрице M замените все отрицательные значения на 0 (прямое изменение исходного массива); выведите M до и после.
# маска (M < 0) и присваивание по маске: M[mask] = 0.
M = np.arange(-3,9)
print(M)
mask = (M > 0)
M[mask] = 0
print(M)

[-3 -2 -1  0  1  2  3  4  5  6  7  8]
[-3 -2 -1  0  0  0  0  0  0  0  0  0]


In [21]:
# примените векторное ветвление к x: если элемент >= 0, заменить на квадрат; иначе — на -1.
# используйте np.where(cond, a, b), где cond = (x >= 0), a = x**2, b = -1.
x = np.array([-3, -1, 0, 1, 2, 3])
y = np.where(x < 0, -1, x*2)
print(y)

[-1 -1  0  2  4  6]


In [24]:
# для матрицы M (3×4) вычислите: (1) сумму всех элементов; (2) суммы по строкам (axis=1); (3) суммы по столбцам (axis=0).
# метод .sum(...); проверьте формы результатов для axis=1 → (3,), axis=0 → (4,).
M = np.array([
[1,2,3,4],
[5,6,7,8],
[9,10,11,12]
])
print(M)
t_sum = M.sum()
print(t_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78


In [26]:
# для матрицы M (3×4) вычислите: (1) среднее по всем элементам; (2) средние по строкам; (3) средние по столбцам.
# метод .mean(...); помните: axis=1 → вдоль строк (форма (3,)), axis=0 → вдоль столбцов (форма (4,)).

M = np.array([
[1,2,3,4],
[5,6,7,8],
[9,10,11,12]
])
t_mean = M.mean()
print(t_mean)
row_mean = M.mean(axis=1) 
print(row_mean)
col_mean = M.mean(axis=0) 
print(col_mean)


6.5
[ 2.5  6.5 10.5]
[5. 6. 7. 8.]


In [27]:
A = np.random.rand(10)
print(A)

[0.86188235 0.03434452 0.2368689  0.17720089 0.46594298 0.39234969
 0.71888962 0.1632744  0.05007489 0.73153848]


In [29]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [31]:
# очень быстрое суммирование
sum_res= np.add.reduce(a)

In [46]:
# максимальный элемент равно нулю
a = np.random.rand(10)
print(a)
b = []
b = a.sort()
print(a[0])
a[9] = 0
print(a)

[0.19905282 0.77330003 0.99107628 0.0522872  0.51296267 0.24208422
 0.21094281 0.48814173 0.71639472 0.46627753]
0.05228719982884189
[0.0522872  0.19905282 0.21094281 0.24208422 0.46627753 0.48814173
 0.51296267 0.71639472 0.77330003 0.        ]


In [14]:
# непонятно что
# arr = np.genfromtxt(input_string.split("\n"),
# delimiter=',',
# dtype = float,
# missing_values='',
# filling_values=np.nan)

# центрированная матрица
import numpy as np
a = np.random.rand(5,3)
print(a)
row_mean = a.mean(axis=1) 
print(row_mean)    
# a_centered = np.subtract(A.T, A_mean).T
a_centered = np.subtract(a.T, row_mean).T
print(a_centered)

# 0 2 4 элементы Дополнить нулями 
X = np.array([1,2,3,4,5])
F = np.zeros([3,5])
I = [0,2,4]
F[:,I] = X[I]
print(F)




[[0.14659796 0.6098615  0.39902034]
 [0.49520533 0.58947351 0.25734913]
 [0.94896609 0.63866597 0.03972678]
 [0.36425704 0.78605562 0.60577098]
 [0.26711528 0.65637282 0.89282145]]
[0.38515993 0.44734266 0.54245295 0.58536121 0.60543652]
[[-0.23856197  0.22470157  0.01386041]
 [ 0.04786267  0.14213086 -0.18999353]
 [ 0.40651315  0.09621302 -0.50272617]
 [-0.22110418  0.2006944   0.02040977]
 [-0.33832124  0.0509363   0.28738493]]
[[1. 0. 3. 0. 5.]
 [1. 0. 3. 0. 5.]
 [1. 0. 3. 0. 5.]]


In [6]:
# дополнить вектор тремя нулями между каждым элементом
x = np.array([1,2,3,4,5])
# y = np.zeros(len(a)*4-3)
y = np.zeros(20)
y[::4]=x
print(y) 



[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


In [8]:
# Из одномерного массива получить двумерный со смещением в единицу
# варианты решения
# решение от Кондратенко Николая
# исходный мсассив
Z = np.array([1, 2, 3, 4, 5, 6 ,7 , 8, 9])
# длина окна - колическиство элементов в каждой строке результата
window_size = 3

# число строк в результирующем массиве (двумерный массив)
num_rows = len(Z) - window_size + 1

# создать подмассивы со смещением в 1 и объединить их
res = np.vstack(Z[i:i+window_size] for i in range(num_rows))
print(res)

res = np.vstack(list(Z[i:i+window_size] for i in range(num_rows)))
print(res)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


C:\Users\Администратор\AppData\Local\Temp\ipykernel_3264\398484308.py:13: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  res = np.vstack(Z[i:i+window_size] for i in range(num_rows))


In [10]:
#  Извлечь уникальные значеня из двух двумерных массивов
import numpy as np
import itertools

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[3, 4], [5, 6]])

# Использование chain.from_iterable для выравнивания
combined_list = list(itertools.chain.from_iterable(array1)) + \
                list(itertools.chain.from_iterable(array2))

unique_values = list(set(combined_list))

print(unique_values)
# Вывод: [1, 2, 3, 4, 5, 6]
# в_2
a = np.array([[1, 2], [3, 4]])
b = np.array([[3, 4], [5, 6]])
np.unique(np.concatenate((np.ravel(a), np.ravel(b))))

[1, 2, 3, 4, 5, 6]


array([1, 2, 3, 4, 5, 6])