In [2]:
# Импортируйте библиотеку nympy
import numpy as np

In [8]:
# Создайте массив-скаляр (0D) со значением 5 и выведите его shape, ndim, dtype и nbytes.
# используйте np.array
import numpy as np
s = np.array(5)
# размерность
print(s.shape)

print(s.ndim)
print(s.dtype)
print(s.nbytes)

(2,)
1
int32
8


In [11]:
# Создайте одномерный нулевой вектор длиной 10 и выведите shape, ndim, dtype, nbytes.
# используйте np.zeros(10)
import numpy as np
s = np.zeros(10)
print(s)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
# Создайте вектор со значениями от 10 до 49 включительно и выведите shape, ndim, dtype, size.
# используйте np.arange(10, 50)
import numpy as np
s = np.arange(10,50)
print(s)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
# Инвертируйте порядок элементов вектора из части 3 (первый элемент становится последним).
# используйте срез [::-1]
import numpy as np
s = np.arange(10,50)
t = s[::-1]
print(t)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [21]:
# Создайте матрицу 3x3 со значениями от 0 до 8.
# используйте np.arange(...).reshape(...)
import numpy as np
s = np.arange(9)
print(s)
s = s.reshape(3,3)
print(s)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
# Найдите индексы ненулевых элементов в массиве [1, 2, 0, 0, 4, 0].
# используйте np.nonzero(...)

s = np.array([1, 2, 0, 0, 4, 0])
print(s)
t = np.nonzero(s)
print(t)

[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)


In [25]:
# Создайте массив 3x3x3 со случайными значениями и выведите shape, ndim, size.
# используйте np.random.rand(3, 3, 3)
s = np.random.rand(3, 3, 3)
print(s)
# размерность
print(s.shape)
# число измерений
print(s.ndim)
print(s.size)
print(s.dtype)
print(s.nbytes)

[[[0.87245156 0.38635314 0.92584238]
  [0.43179431 0.10947106 0.31047567]
  [0.38995136 0.38049898 0.63775524]]

 [[0.629955   0.67897819 0.07854092]
  [0.19756561 0.5335377  0.5901383 ]
  [0.76936036 0.49449473 0.30085455]]

 [[0.07283035 0.87329851 0.63149643]
  [0.30583437 0.97094157 0.99774901]
  [0.27346183 0.59520361 0.64010527]]]
(3, 3, 3)
3
27
float64
216


In [26]:
# Создайте массив 10x10 со случайными значениями и найдите в нём min и max.
# используйте np.random.rand(10, 10), np.min(...), np.max(...)
s = np.random.rand(10, 10)
print(s)
max_s = np.max(s)
print(max_s)
mon_s = np.min(s)
print(min_s)

[[0.85592255 0.28025312 0.23831169 0.89510171 0.79393283 0.40715383
  0.35288167 0.50798487 0.99247932 0.76353452]
 [0.78237038 0.79703805 0.94381719 0.7482043  0.80801254 0.30862161
  0.51805301 0.94754227 0.75118434 0.62380686]
 [0.39437744 0.56991866 0.88985019 0.05827549 0.53666248 0.45411695
  0.50912805 0.05014505 0.8296952  0.74838867]
 [0.39050754 0.28515802 0.97363938 0.52027153 0.3970238  0.17472973
  0.05053671 0.19863174 0.73617205 0.92674429]
 [0.13522587 0.14349632 0.56453865 0.29344613 0.13089907 0.37431543
  0.83793076 0.13321008 0.09878578 0.04644582]
 [0.19814559 0.06392417 0.56896697 0.02473773 0.69525841 0.38874324
  0.69753682 0.15388604 0.30104544 0.01292763]
 [0.19488376 0.62866376 0.57222696 0.84985857 0.50406521 0.8649167
  0.95337924 0.76271084 0.21936064 0.51541194]
 [0.86739509 0.60388243 0.63159298 0.27237792 0.08445968 0.94313146
  0.20905561 0.76656969 0.64647445 0.4511876 ]
 [0.13744424 0.3324331  0.96797457 0.0298388  0.74620019 0.91757145
  0.88879463 

In [28]:
# Создайте случайный вектор размера 30 и найдите его среднее значение.
# используйте np.random.rand(...) и np.mean(...)
s = np.random.rand(30)
print(s)
mean_s = np.mean(s)
print(mean_s)

[0.63383992 0.77786988 0.55190245 0.8502166  0.84596377 0.78415852
 0.65805063 0.98069214 0.21837932 0.30956715 0.12353463 0.1735031
 0.16945562 0.45892292 0.12332419 0.53444876 0.37599617 0.36866357
 0.56605826 0.68811874 0.41155288 0.93788466 0.21708805 0.86027888
 0.49659383 0.65827049 0.91448218 0.2549704  0.55568267 0.81132034]
0.5436930247367544


In [33]:
# Создайте массив 3x3 с единицами по границе и нулями внутри.
# используйте np.ones(...) и срез a[1:-1, 1:-1] = 0
s = np.ones((3,3))
print(s)
s[1:-1,1:-1]=0
print(s)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [43]:
# Для массива формы (6, 7, 8) найдите индекс (x, y, z) 100-го элемента (нумерация с 0).
# используйте np.unravel_index(99, (6, 7, 8))
s = np.zeros((6,7,8))
print(s)
idxes = np.unravel_index(99, (6,7,8))
print(idxes)


[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0

In [44]:
# Перемножьте матрицу A (5x3) на матрицу B (3x2), выведите форму результата и сам результат.
# Подсказка: используйте оператор @ или np.dot(A, B)
A = np.random.rand(5, 3)
print(A)
# Матрица B размером 3x2
B = np.random.rand(3, 2)
print(B)
C = np.dot(A,B)
print(C)

[[0.25916088 0.97996965 0.86044269]
 [0.37004589 0.25150364 0.13640744]
 [0.72174043 0.61633584 0.11119248]
 [0.7520417  0.73791324 0.04305193]
 [0.2996772  0.80736708 0.44063239]]
[[0.13929719 0.28407725]
 [0.25469874 0.13753267]
 [0.58408175 0.97218215]]
[[0.78826629 1.04490658]
 [0.19527711 0.27232447]
 [0.32246187 0.39789569]
 [0.31784871 0.35697943]
 [0.50474491 0.62454577]]
